11820 employee view
LeadWinnerOrg/squareupApiTest pull request #7
Opened 2023-05-19 12:58 UTC by bhanu-Lwc

Creating pull Request for Employee View API
1. Created Feature file for Employee View API
2. Created pojo class for response 
3. Written API Request in Endpoint Class
4. Validated Response in StepDefination

2023-05-22 04:15 UTC, souravdasbitm requested changes

2023-05-22 04:15 UTC, souravdasbitm commented on src/test/java/stepDefinitions/EmployeeOperationSteps.java
> +        Assert.assertEquals(dataTable.cell(14, 1), employeeView.getResponse().getMobilePermissions().get(1).getTitle());
Duplicate Code

2023-05-22 04:15 UTC, souravdasbitm commented on src/test/resources/functionalTestCases/EmployeeView.feature
> +      | title                                        | Project Details View                  |
Duplicate

2023-05-23 16:09 UTC, souravdasbitm reviewed
@bhanu-Lwc did you updated the changes which was requested.

2023-05-24 03:41 UTC, souravdasbitm approved these changes

2023-05-24 03:42 UTC, jeeva666 approved these changes

2023-05-24 03:42 UTC, merged